config/routes.rb
Brief::Application.routes.draw do
  resources :forms do
    resources :comments
  end
  root "index#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :form
end

app/models/data_file.rb
class DataFile < ActiveRecord::Base
  belongs_to :form
end

app/models/form.rb
class Form < ActiveRecord::Base
  #attr_accessor :image_file_name, :image_content_type, :image_file_size, :image_updated_at

  has_many :comments, dependent: :destroy
  has_one :data_file
  has_attached_file :image,
                    :styles => { :medium => "300x300>", :thumb => "100x100>" },
                    :path => ":rails_root/public/attachments/:attachment/:id/:style/:filename",
                    :url => "/attachments/:attachment/:id/:style/:filename",
                    :default_url => "/images/:style/missing.png"
  validates :title, presence: true,length: { minimum: 5 }
  validates :email, email_format: { message: "doesn't look like an email address" }
  validates_attachment_content_type :image, :content_type => %w(image/jpeg image/jpg image/png)

  # send email
 # after_create do |form|
    #FormMailer.new_request(form).deliver
  #end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @form = Form.find(params[:form_id])
    @comment = @form.comments.create(params[:comment].permit(:commenter, :body))
    redirect_to form_path(@form)
  end

  def destroy
    @form = Form.find(params[:form_id])
    @comment = @form.comments.find(params[:id])
    @comment.destroy
    redirect_to form_path(@form)
  end
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "adminpass", only: [ :show]

  def index
    @forms = Form.all
  end

  def new
    @form = Form.new
  end

  def show
    @form = Form.find(params[:id])
    MainsmsApi::Configuration.setup project: 'Brief', api_key: 'a968e12fd7c59'
    message = MainsmsApi::Message.new(sender: 'sendertest', message: 'From Russia with love', recipients: ['89051492237'])
    response = message.deliver
  end

  def create
    @form = Form.new(form_params)

    if @form.save
      # Tell the FormMailer to send a welcome Email after save
      FormMailer.new_request(@form).deliver
      #Send sms
      SMS.text :message => "Hello!", :to => "+79045958616"
      #form.html { redirect_to(action: :show, id: @form.id, notice: 'Request was successfully created.') }
     # form.json { render json: @form, status: :created, location: @form }
      #redirect_to action: :show, id: @form.id
      render 'show'
    else
      render 'new'
    end
  end

  def edit
    @form = Form.find(params[:id])
  end

  def update
    @form = Form.find(params[:id])

    if @form.update(params[:form].permit(:title, :email, :service, :kind, :style, :content, :text, :image))
      redirect_to @form
    else
      render 'edit'
    end
  end

  def destroy
    @form = Form.find(params[:id])
    @form.destroy

    redirect_to action: :index
  end

  private

  def form_params
    params.require(:form).permit(:title, :email, :service, :kind, :style, :content, :image, :text)
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.form, comment],
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@form, @form.comments.build]) do |f| %>
    <p>
      <%= f.label :commenter %><br />
      <%= f.text_field :commenter %>
    </p>
    <p>
      <%= f.label :body %><br />
      <%= f.text_area :body %>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/forms/_form.html.erb
<%= form_for @form do |f| %>
    <% if @form.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@form.errors.count, "error") %> prohibited
            this form from being saved:</h2>
          <ul>
            <% @form.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>

    <p>
      <%=f.label :service %><br>
      <%=f.select(:service, options_for_select([['Бизнес', 'business'], ['Недвижимость', 'real estate'], ['Кино', 'cinema'], ['Авто', 'cars']])) %>
    </p>

    <p>
      <%=f.label :kind %><br>
      <%=f.select(:kind, options_for_select([['Корпоративный сайт', 'Corporate website'], ['Интернет-магазин', 'Online shop'], ['Промо-сайт продукта', 'Promo-site product'], ['Сайт-визитка', 'Online Business Card']])) %>
    </p>

    <p>
      <%= f.label :style %>
      <%= f.check_box :style %> Наличие фирменного стиля
    </p>

    <%= f.radio_button(:content, "photo") %>
    <%= f.label(:content, "Фото") %>
    <%= f.radio_button(:content, "video") %>
    <%= f.label(:content, "Видео") %>
    <%= f.radio_button(:content, "audio") %>
    <%= f.label(:content, "Аудио") %>

    <p>
      <%= f.label :image %>
      <%= f.file_field :image %>
    </p>

    <p>
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </p>

    <p>
      <%= f.label :text %><br>
      <%= f.text_area :text %>
    </p>

    <p>
      <%= f.submit %>
      <%= link_to 'Отмена', @form %>
    </p>
<% end %>

app/views/forms/edit.html.erb
<h1>Редактирование заявки на создание сайта № <%= @form.id %></h1>

<%= render 'form' %>

<%= link_to 'Back', forms_path %>

app/views/forms/index.html.erb
<h1>Список заявок</h1>

<table>
  <tr>
    <th>Компания</th>
    <th>Дата</th>
  </tr>

  <% @forms.each do |form| %>
      <tr>
        <td><%= form.title %></td>
        <td><%= link_to 'Show', form %></td>
        <td><%= link_to 'Edit', edit_form_path(form) %></td>
        <td><%= link_to 'Destroy', form_path(form),
                        method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
  <% end %>
</table>

<p><%= link_to "Новая заявка", new_form_path %></p>

app/views/forms/new.html.erb
<h1>Заполните бриф на создание сайта</h1>

<%= render 'form' %>

<%= link_to 'Back', forms_path %>

app/views/forms/show.html.erb
<h1>Заявка на создание сайта № <%= @form.id %></h1>
<h3>Дата заполнения: <%= @form.created_at.strftime("%d %b. %Y %H:%M") %></h3>

<p>
  <strong>Название компании:</strong>
  <%= @form.title %>
</p>

<p>
  <strong>Cфера деятельности:</strong>
  <%= @form.service %>
</p>

<p>
  <strong>Тип web-проекта:</strong>
  <%= @form.kind %>
</p>

<p>

  <strong>Наличие фирменного стиля:</strong>
  <%= @form.style %>
</p>

<p>
    <strong>Тип контента:</strong>
    <%= @form.content %>
</p>

<% #if @form.data_file.size>0 %>
    <!--<p><a href="/upload/<%#= data_file.path %>"><%#= data_file.path %></a></p>-->
<% #end %>

<p>
    <strong>Изображение:</strong>
    <a href="<%=@form.image.url %>"><%=image_tag @form.image.url(:medium) %></a>
</a>
</p>

<p>
  <strong>E-mail:</strong>
  <%= @form.email %>
</p>

<p>
  <strong>Описание проекта:</strong>
  <%= @form.text %>
</p>

<h2>Comments</h2>
<%= render @form.comments %>


<h2>Add a comment:</h2>
<%= render "comments/form" %>

<%= link_to 'Back', forms_path %>
| <%= link_to 'Edit', edit_form_path(@form) %>

app/views/index/index.html.erb
<h2>Заполните наш бриф на создание сайта и мы предложим вам оптимальное решение для вашего проекта!</h2>
<%= link_to "Заполнить бриф онлайн", new_form_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Brief</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device=width, initial-scale=1.0, maximum-scale=1.0">
  <title>Index</title>
  <!--all styles-->
  <link rel="stylesheet" type="text/css" href="css/all.css">
  <!--media styles-->
  <link rel="stylesheet" type="text/css" href="css/media.css">
  <!--jQuery library-->
  <script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
  <!--include plugins-->
  <script src="js/plugins/jquery.mousewheel.min.js"></script>
  <script src="js/plugins/jquery.easing.1.3.js"></script>
  <script src="js/plugins/jquery.mCustomScrollbar.min.js"></script>
  <script src="js/plugins/hammer.1.0.5.js"></script>
  <script src="js/plugins/masonry.pkgd.min.js"></script>
  <script src="js/jquery.img-stretch.js"></script>
  <script src="js/jquery.carousel.js"></script>
  <script src="js/jquery.main-gallery.js"></script>
  <script src="js/jquery.add-class.js"></script>
  <script src="js/jquery.custom-select.js"></script>
  <script src="js/jquery.init-plugins.js"></script>
  <script src="js/jquery.form-validator.js"></script>
  <!--common javascript-->
  <script src="js/common.js"></script>
  <!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <script src="js/plugins/respond.min.js"></script>
  <![endif]-->
</head>
<body class="loaded no-gallery inner-page">
    <div id="wrapper">
      <!--header starts-->
      <header id="header" data-func="cols-show">
        <div class="container">
          <h1 class="logo"><a href="#">Rocketmind</a></h1>
          <a class="opener" href="#">Opener</a>
        </div>
      </header>
      <section class="top-bar">
        <div class="container cols">
          <nav id="nav">
            <strong class="title">Navigate</strong>
            <ul>
              <li><a href="#">About</a></li>
              <li><a href="#">Services</a></li>
              <li><a href="#">Works</a></li>
              <li><a href="#">Contacts</a></li>
            </ul>
          </nav>
          <div class="col">
            <strong class="title">Latest work</strong>
            <figure>
              <img src="images/content/img-projects-8.jpg" alt="" width="256" height="256">
              <figcaption>
                <strong class="name">Aeroexpress corporation</strong>
                <ul>
                  <li><a href="#">Digital marketing</a></li>
                  <li><a href="#">Branding</a></li>
                  <li><a href="#">Mobile development</a></li>
                </ul>
              </figcaption>
            </figure>
          </div>
        </div>
        <div class="container form">
          <form class="feedback" novalidate action="#">
            <header>
              <h2>Tell about your project</h2>
              Are you interested in working with Rocketmind? Please tell your idea.
            </header>
            <fieldset>
              <div class="box">
                <label for="name">Your name</label>
                <input type="text" id="name">
                <span class="status">Error</span>
                <em class="note">You must fill all the details!</em>
              </div>
              <div class="box">
                <label for="email">Your e-mail</label>
                <input type="email" id="email">
                <span class="status">Error</span>
                <em class="note">You must fill all the details!</em>
              </div>
              <div class="box">
                <label for="select">Select</label>
                <div class="select">
                  <select data-placeholder="Select option" id="select">
                    <option selected>Select option</option>
                    <option>Request goal 1</option>
                    <option>Request goal 2</option>
                  </select>
                </div>
              </div>
            </fieldset>
            <fieldset>
              <div class="box alt">
                <label for="message">Your message</label>
                <textarea id="message" cols="80" rows="5"></textarea>
                <input type="submit" value="Send">
              </div>
            </fieldset>
          </form>
        </div>
        <div class="container subscribe-form">
          <form class="feedback subscribe" novalidate action="#">
            <header>
              <h2>Newsletter</h2>
              34567 already subscribed, join our newsletter
            </header>
            <fieldset>
              <div class="box">
                <label for="name-2">Your name</label>
                <input type="text" id="name-2">
                <span class="status">Error</span>
                <em class="note">You must fill all the details!</em>
              </div>
              <div class="box">
                <label for="email-2">Your e-mail</label>
                <input type="email" id="email-2">
                <span class="status">Error</span>
                <em class="note">You must fill all the details!</em>
              </div>
              <div class="box">
                <input type="submit" value="Subscribe">
              </div>
            </fieldset>
          </form>
        </div>
      </section>
      <!--header ends-->
      <!--main starts-->
      <div id="main">
        <section class="services-info">
          <div class="item">
            <div class="item-holder">
              <div class="item-box">
                <section class="item-info">
                  <div class="img-holder">
                    <%= image_tag "content/img-services-gallery-31.png", {width: 345, height: 218} %>
                  </div>
                  <div class="wrap">
                    <h2>Request</h2>
                    <p><%= yield %></p>
                  </div>
                </section>


              </div>
            </div>
          </div>
        </section>
    </div>
    <!--main ends-->
    <!--footer starts-->
    <footer>
      <div class="container">
        <ul class="add-info">
          <li><p class="copy">&copy; 2005-2014 Rocketmind</p></li>
          <li><address>37 Leningradsky prospect, Moscow, Russia</address></li>
          <li>+7 495 123-45-67</li>
          <li><a href="mailto:hello@rocketmind.ru">hello@rocketmind.ru</a></li>
        </ul>
      </div>
    </footer>
    <!--footer ends-->
    </div>
    <!--wrapper ends-->
</body>
</html>